remove notification key from FCM payload
bluecherrydvr/bluecherry-mobile-notification-hook pull request #2
Opened 2022-06-27 14:30 UTC by alexmercerind

In Flutter version of the application, we show the notifications programmatically because custom image & buttons are added into the notification (controlled entirely inside Dart/Flutter code).

Having `notification` in the FCM payload causes the Firebase to show notification automatically (with no control over it). This in turn, causes the application to show same notification twice (one from the Firebase without any buttons or image & the other one sent by Flutter).

Now the `data` inside the payload is consumed to show the notification & other details present in it.

Reference: https://github.com/firebase/flutterfire/discussions/6113.

It'll be likely better to have this in a separate branch.

2022-06-28 10:27 UTC, alexmercerind commented
Notifications issued by our client app have higher priority (in general).

We need the application to be "awaken" from background for sending notifications from Flutter, because we are only consuming the data from payload (and not notification). `contentAvailable: true` causes inactive client app on iOS to be awoken. On Android, data messages wake the app by default.

`priority: 'high'` makes the `data` to be received immediately on the client app. By default, `data`-only payload shows with `priority: 'normal'` (causes some unspecified delay, battery-consumption etc). Since, `notification` key is now removed from the payload, it is important to set the `priority` to `high` explicitly.

A discussion regarding this can be seen at:
https://github.com/firebase/flutterfire/issues/8277#issuecomment-1152535863
https://firebase.google.com/docs/cloud-messaging/http-server-ref

<hr></hr>

Let's hope it works.

2022-06-30 19:06 UTC, tugrul reviewed
Did you try to use background message handler on the client side?

2022-06-30 19:06 UTC, tugrul commented on index.js
> -        notification: {
removing this section can broke actual mobile app

2022-06-30 19:06 UTC, tugrul commented on index.js
> -        notification: {
removing this section can broke actual mobile app

2022-06-30 19:06 UTC, tugrul commented on index.js
> -        notification: {
removing this section can broke actual mobile app

2022-07-06 14:18 UTC, alexmercerind commented
Hey @tugrul, may you please review the pull-request again.

I exposed `disable_payload_notification` in the /store-token POST body.

If this is passed `true` ([see here](https://github.com/bluecherrydvr/unity/blob/fce2aad3213298f70e91eb549a71699826e5c6e4/lib/api/api.dart#L220)), then notification won't be included in the FCM payload object.
I hope everything is correct & won't break the React Native version of the application now.

Thanks!

2022-07-06 14:19 UTC, alexmercerind commented
> Did you try to use background message handler on the client side?

Yeah.

2022-07-12 23:13 UTC, tugrul requested changes

2022-07-12 23:13 UTC, tugrul commented on index.js
> +            clientTokensWithNotification.push(clientTokens[key]);
make this separation before method call. this cause bloated code.

2022-07-12 23:13 UTC, tugrul commented on index.js
> +            clientTokensWithNotification.push(clientTokens[key]);
make this separation before method call. this cause bloated code.

2022-07-12 23:13 UTC, tugrul commented on index.js
> +            clientTokensWithNotification.push(clientTokens[key]);
make this separation before method call. this cause bloated code.

2022-07-12 23:13 UTC, tugrul commented on index.js
split clientTokens two groups of array by clientDisablePayloadNotifications

2022-07-12 23:13 UTC, tugrul commented on index.js
> +        admin.messaging().sendToDevice(clientTokensWithoutNotification, {
make new method for this like `handleMotionEventWithoutNotification`

2022-07-12 23:13 UTC, tugrul commented on index.js
> +        admin.messaging().sendToDevice(clientTokensWithoutNotification, {
make new method for this like `handleDeviceStateWithoutNotification`

2022-07-12 23:13 UTC, tugrul commented on index.js
> +        admin.messaging().sendToDevice(clientTokensWithoutNotification, {
make new method for this like `handleSoloWithoutNotification`

2022-07-12 23:13 UTC, tugrul commented on index.js
> -            await handleMotionEvent(clientTokens, req.body);
don't remove `await handleMotionEvent(clientTokensWithNotification, req.body);` call it with notification array.

2022-07-12 23:13 UTC, tugrul commented on index.js
> +            await handleMotionEvent(clientTokens, clientDisablePayloadNotifications, req.body);
call here `await handleMotionEventWithoutNotification(clientTokensWithoutNotification, req.body);`

2022-07-12 23:13 UTC, tugrul commented on index.js
> -            await handleDeviceState(clientTokens, req.body);
don't remove await `await handleDeviceState(clientTokensWithNotification, req.body);` call it with notification array.

2022-07-12 23:13 UTC, tugrul commented on index.js
> +            await handleDeviceState(clientTokens, clientDisablePayloadNotifications, req.body);
call here `await handleDeviceStateWithoutNotification(clientTokensWithoutNotification, req.body);`

2022-07-12 23:13 UTC, tugrul commented on index.js
> -            await handleSolo(clientTokens, req.body);
don't remove `await handleDeviceState(clientTokensWithNotification, req.body);` call it with notification array.

2022-07-12 23:13 UTC, tugrul commented on index.js
> +            await handleSolo(clientTokens, clientDisablePayloadNotifications, req.body);
call here `await handleSoloWithoutNotification(clientTokensWithoutNotification, req.body)`;

2022-07-14 08:04 UTC, alexmercerind commented
Hi @tugrul!
I've addressed all the requested changes.
Could you please have a look / review again.

Thanks!

2022-07-15 18:07 UTC, tugrul commented
Thank you @alexmercerind. Looks good.

Can you combine all four commits into one commit? You can use interactive rebase functionality of git for this. https://www.youtube.com/watch?v=JkpYvXdbnfQ

2022-07-16 06:10 UTC, alexmercerind commented
> Thank you @alexmercerind. Looks good.
> 
> Can you combine all four commits into one commit? You can use interactive rebase functionality of git for this. 

Thanks! There's only one commit now.

2022-07-16 11:50 UTC, tugrul approved these changes

2022-07-16 11:50 UTC, merged